### ISSUE TITLE
error retrieving or creating kvm: error checking for kvm istio, status code: 401

### ISSUE THREAD

**Issue by lukemao** [apigee/istio-mixer-adapter#229]
tried to run:

```
apigee-istio provision -o $APIGEEORG -e $APIGEEENV -u $APIGEEUSERNAME -p $APIGEEPWD > /root/apigee-istio-adapter/samples/apigee/handler.yaml
```

In terraform.

Error:

```
error retrieving or creating kvm: error checking for kvm istio, status code: 401
```

Later on, log into the VM and then run manually, worked.

echoed $APIGEEPWD and $APIGEEUSERNAME values all fine

**Comment by lukemao** [comment]
apigee-istio version: 1.0.3-2

**Comment by khurlbut** [comment]
I am getting this same error.

**Comment by khurlbut** [comment]
Is the result of apigee-istio provision *only* the yaml file? Can I skip this step and manually create the yaml file?

**Comment by theganyo** [comment]
Note: If you are upgrading, please provision with the `--forceProxyInstall` option.

The provision command basically does the following:

1. creates a KVM to hold your certificates if necessary
2. creates the certificates and stores them in the KVM
3. creates (or updates/replaces, if you use `--forceProxyInstall`) a proxy in your organization called "istio-auth"
4. verifies the proxy endpoints are working
5. generates and emits the handler yaml configuration

So, yes, you can just create a yaml file... but it's important to know that your installation succeeded. With this error, it may have been that the provisioning worked and there was just an error verifying that the Apigee KVM was created during the provisioning. 

You can run using the `--verbose` option to get more information on what's happening during provisioning.

**Comment by khurlbut** [comment]
I think the 401 was due to permissions error.

I now get 404 error. My organization is 'commerce' and my environment is 'prod' (this is a sandbox - prod is not really prod).

-------------------------------------------------------------------------------------------------
Here's what I get...

checking if proxy edgemicro-internal deployment exists...
GET /v1/o/commerce/apis/edgemicro-internal/deployments HTTP/1.1
Host: dgapigeesbmanagementserver001.rcc.gapinc.dev:9000
User-Agent: go-apigee-edge/0.1.0
Accept: application/json
Authorization: Basic a2V2aW5faHVybGJ1dEBnYXAuY29tOmYyQUM5SGZqanUwMDYxMjE=
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Cache-Control: no-cache
Content-Security-Policy: frame-ancestors 'none'
Content-Type: text/html; charset=utf-8
Date: Mon, 07 Jan 2019 21:34:42 GMT
Strict-Transport-Security: max-age=86400
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1
