### ISSUE TITLE
Problem setting up istio with apigee

### ISSUE THREAD

**Issue by jeson114** [apigee/istio-mixer-adapter#90]
After following the instructions on the README.md i end up with a with Permission denied . Invalid Api key . Also there is no mention of adding istio-auth proxy from the release folder . But i did manage to add that too  and i get the correct response for exactly two requests . Every time i make a change to the proxy . it works for a another couple of requests and throws Denied again

**Comment by theganyo** [comment]
Hey Jeson. Sorry you're having some issues. I'm not sure what's going on, but I can tell you that the proxy in the release folder is not for you. :) I'm getting ready to release an alpha-2 in a day or two and it will be used for the new version... and is likely not compatible with the old in certain ways. Instead, you should be using a proxy installed by edgemicro. So, I'd start over from there. On the other hand, if you can, it may be better to simply wait a couple of days for the new version and work from there.

**Comment by aswinsegu** [comment]
- The mapIdentifier is pointing to Isito where as the KVM name is microgateway
- key names in KVMs and policy dont match
- getting following error due to the above mismatch
PERMISSION_DENIED:apigee-handler.apigee.istio-system:verifyJWT(): jwt.Parse(): failed to fetch remote JWK (status != 200)
- no documentation on which proxy to deploy or either a proxy need to be deployed
- the api endpoint "/istio-auth/jwkPublicKeys" does not exist in istio-auth
- After fixing all the above, facing following issue
PERMISSION_DENIED:apigee-handler.apigee.istio-system:verifyJWT(): jwt.Parse(): jwks doesn't contain key: 1

**Comment by theganyo** [comment]
Are you attempting to compile and install from source instead of using the release? All of the issues you’re running into are a result of our transitioning from alpha-1 to alpha-2. They are not compatible and I don’t recommend working from source right now.

**Comment by theganyo** [comment]
I just realized you might also be attempting to run from the nightly build as that’s mentioned in the readme. Don’t do that either right now, it’s incompatible with the alpha-1 proxy.

**Comment by aswinsegu** [comment]
We are using release and not from nightly, still we are not able to setup properly due to the above issues

**Comment by jeson114** [comment]
@theganyo  Setting it to /edgemicro-auth worked . Thanks a lot :)
